
# Disable automatic AppVeyor build logic
build: off

image:
  - Visual Studio 2019
  - Ubuntu1604
  - macos

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
    - choco install -y winpcap
  build_script:
    - dotnet build -c Release
  test_script:
    - dotnet test --test-adapter-path:. --logger:Appveyor

-
  matrix:
    only:
      - image: Ubuntu1604
  install:
    - sudo apt-get -qy install libpcap-dev
  test_script:
    - sudo dotnet test --test-adapter-path:. --logger:Appveyor -f netcoreapp2.1 --filter TestCategory!=SendPacket

-
  matrix:
    only:
      - image: macos
  install:
    - brew update
    - brew install libpcap
  test_script:
    - sudo dotnet test --test-adapter-path:. --logger:Appveyor -f netcoreapp2.1
