
# Disable automatic AppVeyor build logic
build: off

image:
  - Visual Studio 2019
  - Ubuntu

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
    - choco install -y winpcap
  build_script:
    - dotnet build -c Release
  test_script:
    - dotnet test -c Release

-
  matrix:
    only:
      - image: Ubuntu
  environment:
    DOTNET_ARGS: 
  install:
    - sudo apt-get -qy install libpcap-dev
  test_script:
    - dotnet test -c Release -f netcoreapp2.1
