version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build -c Release

  test-libpcap:
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1-buster'
    steps:
      - checkout
      - run:
          name: Install
          command: sudo apt-get install -y libpcap-dev
      - run:
          name: Test
          command: dotnet test -c Release -f netcoreapp2.1


workflows:
  version: 2
  build:
    jobs:
      - build
      - test-libpcap
